### ISSUE TITLE
[FEATURE] Check for updates

### ISSUE THREAD

**Issue by Myzel394** [Myzel394/locus#14]
## 0 - 14 days of being outdated
Show a banner at the top, dismissible

## 14 - 30 days of being outdated
Show a banner at the top, not dismissible

## 30 - 60 days of being outdated
Show a dialog at the start

## > 60 days of being outdated
Disable app, only show outdated warning at app opening

**Comment by Myzel394** [comment]
Regarding this, I think it makes sense to build a special version for F-Droid. If the user manually downloads the APK, they should be able to click on the banner and Locus will then download the newest APK automatically. If the user is on F-Droid however, he should be sent to the F-Droid store. @IzzySoft what do you think?

**Comment by Myzel394** [comment]
> Note that on F-Droid.org, integrated updaters are frowned upon (it's the job of the "store client" to take care for that). So if you want to integrate one, better make sure it's opt-in

That makes sense, I think I'll add this only on the GitHub releases then, because there is no store that checks for updates.

> And I'd strongly discourage from the last step (disabling the app). There might be good reasons why one might not want to update, you shouldn't enforce this

I honestly don't know any good reasons not to update an app. Updates may contain important security fixes, so it's important to keep an app up to date. If an user has not updated an app for over two months, they are running quite an old app and I personally think we need to push them to install the newer version without any security flaws. We could however increase this to 90 days for example.

**Comment by IzzySoft** [comment]
> because there is no store that checks for updates.

If you don't count my repo, which gets the APKs from there – and uses the F-Droid client… :wink:

> any good reasons not to update an app

* I'm abroad in a country where additional data fees apply, and thus want to keep the data volume low
* I'm traveling in an area without a WiFi I'd trust and have to take care for my data volume
* a feature you added breaks my workflow
* the new version is for some reasons incompatible with my device, or causes other problems
* an update cannot be installed for some technical reasons (e.g. downloads failing)

All of these I've already experienced myself. It's a personal choice if I prefer a certain version, and a personal choice if and when I want to update. If you force me to a behavior I don't want, it limits my freedom – and the question arises if it might violate one of the [4 freedoms](https://en.wikipedia.org/wiki/Free_and_open-source_software#Four_essential_freedoms_of_Free_Software) FOSS grants (here: freedom-0, "The freedom to run the program as you wish").

> Updates may contain important security fixes

Yes, they *may* – and you then should inform about it in your release notes. It's still **my** decision.

> we need to push them to install the newer version

So you say the people are too stupid (sorry) to make their own decisions, and you have to decide for them? No offense meant of course, but if I feel like that, I'd not use such software but switch to an alternative that does not press me. If I have the feeling a dev considers me immature and incompetent (again, no offense meant), I loose trust in them. And in their software. And if I run into "issues" because of not acting on a security update, I cannot blame you but it's all my fault :wink:

So again, I'd strongly discourage that. Putting on a warning is fair and good, but enforcing action is not, IMHO. Good intentions, yes – but not the right approach.

**Comment by Myzel394** [comment]
> So you say the people are too stupid (sorry) to make their own decisions, and you have to decide for them?

To be honest: Yes. However, adding this feature I was not thinking about someone who knows how Android works and how GitHub works (like you) - but rather someone like my grandmother. Just a few weeks ago she asked me what "To unlock, please swipe" means... However, I think showing a dialog with an explanation will probably be the best option, because...

> I'm abroad in a country where additional data fees apply, and thus want to keep the data volume low
I'm traveling in an area without a WiFi I'd trust and have to take care for my data volume
a feature you added breaks my workflow
the new version is for some reasons incompatible with my device, or causes other problems
an update cannot be installed for some technical reasons (e.g. downloads failing)

convinced me. Based on that, I'd suggest the following approach:

**0 - 3 days**
No dialog, no banner, nothing. Most users usually keep their app up-to-date, so we should give the stores a few days to show a notification.

**4 - 30 days**
Show a dismissible banner at the top of the app

**30+ days**
Show a dialogue only one time at the start of the app explaining the apps will likely have bugs. The user should know by now, that there is an update available.

**Comment by Der-Flip** [comment]
> dialogue only one time at the start of the app

My non-dev 2cts on this:

I'd suggest a "don't show this again" checkbox because if for some reason anything prevents a user to update permanently (incompatibility, workflow, god knows what) getting this box every launch can be quite annoying. If you want to put some emphasis on the dialogue I would say first time dialogue shows 5 second countdown until ok / dismiss button becomes clickable, after that, it's immediately dismissable but at all stages (first and n-th time shown) the user may select the do-not-show-again-checkbox.
You could still give a not too flashy note in the about / settings pages to inform the user permanently there's an update available.

> To be honest: Yes.

generally I agree, you need to design for what we in German call the DAU*, but i'd also argue that those people most likely would never want an app that shares their location let alone all the nostr infrastructure which would already go right over their heads... So I think you a perfectly fine to assume some intelligence for the people that use your app :P

_*dümmster anzunehmender User (most stupid user conceivable), derived from GAU (größter anzunehmender Unfall [maximum conceivable accident])_

**Comment by Myzel394** [comment]
> I'd suggest a "don't show this again" checkbox

That's a good idea, I'll go with that, thanks for your 2 cents! :D

> you need to design for what we in German call the DAU*, but i'd also argue that those people most likely would never want an app that shares their location let alone all the nostr infrastructure which would already go right over their heads

Yes that's true, my grandmother would certainly not understand Nostr at all :D

**Comment by IzzySoft** [comment]
> but rather someone like my grandmother.

Never underestimate grandmothers. They might one day surprise you :see_no_evil:

> my grandmother would certainly not understand Nostr at all

See? So not the best example, huh? :see_no_evil:

> convinced me.

Great! Now may I *suggest* a slightly different timing for the 3 intervals: 0-7, 8-30, beyond? Not that important anymore as the actions seem sound, but 3 days is nothing (if you want an argument: the next week-end has 3 days you spent with a) relatives or b) friends-partying, getting sober on day 4… :speak_no_evil: :dash: 

> I'd suggest a "don't show this again" checkbox

:100: for exactly that reason you named :smile:

**Comment by Korb** [comment]
The "Check for updates" button is needed in an application distributed via GitHub. At least until a version using Google Play Services appears on Google Play or F-Droid. And I am against embedding an update into the application itself. The right to install applications on a mobile device should generally only be granted to application store client applications, and the granting of such permission by another application should be seriously justified. Justified, for example, by the functions of the application, due to which existing application stores refuse to host it. Locus, as far as I know, does not have such functions.

**Comment by IzzySoft** [comment]
> At least until a version using Google Play Services appears on Google Play or F-Droid.

A version using Google Play Services will never appear on F-Droid. Those are proprietary and should not be part of a FOSS app. Just saying :wink:

**Comment by Myzel394** [comment]
> A version using Google Play Services will never appear on F-Droid. Those are proprietary and should not be part of a FOSS app

I do plan to publish a version for the Google Play Store. It will be the GMS variant, but the free FLOSS variant will still be available to download of course.

**Comment by Korb** [comment]
> A version using Google Play Services will never appear on F-Droid. Those are proprietary and should not be part of a FOSS app.

F-Droid has apps that use non-free services. Simply, they are provided with the appropriate mark.

**Comment by IzzySoft** [comment]
@Korb there's a difference between "using" and "containing". The former is `NonFreeDep` (depends upon but doesn't contain it itself), the latter would be `NonFreeComp` (contains it itself and hence is not eligible for F-Droid.org – this anti-feature is only available in my repo and only accepted with limited scope, but strongly discouraged there and should not take place).

**Comment by Korb** [comment]
@IzzySoft, thank you for the clarification.  Locus using Google location service may not contain non-free services to be able to be placed in the F-Droid directory?

**Comment by Myzel394** [comment]
>  Locus using Google location service

Locus does not use GMS in the FLOSS version
