### ISSUE TITLE
Different Locus apps found - are they related to this?

### ISSUE THREAD

**Issue by NicoCharrua** [Myzel394/locus#67]
Is https://live-tracking.locusmap.app/how-it-works/ related to this project? Because if it isn't, then there are two different location tracking apps called Locus which seems kinda strange.

And also if i google even 'Locus Github' i get a bunch of other projects as well as this one, two of which also have to do with location.

This app looks great, and I hope I'll be able to use it in the future, but I'm worried it might get buried under apps with similar names. Or maybe I'm misunderstanding something.

**Comment by Myzel394** [comment]
Hi @NicoCharrua,

Locus (my Locus) only features the app on this repo and the domain https://locus.cfd. The link you sent has nothing to do with my app.

> And also if i google even 'Locus Github' i get a bunch of other projects as well as this one, two of which also have to do with location.

I actually couldn't find any other apps :O I only found some things related to lasers and https://github.com/BirjuVachhani/locus-android - this actually looks promising for Kotlin development - thanks for the indirect hint! :D

> This app looks great, and I hope I'll be able to use it in the future, but I'm worried it might get buried under apps with similar names. Or maybe I'm misunderstanding something.

I'm sorry if that caused confusion - at least the locus you sent uses a different logo, maybe you can distinguish them by the logo? Otherwise you could also just use this Locus here, then there would be no confusion at all :D

**Comment by NicoCharrua** [comment]
This is what I mean by other apps
![Screenshot1](https://github.com/Myzel394/locus/assets/55714525/9f3cf653-bf85-43dc-8631-88021cb75b49)
It might be a little confusing for non technical users to find the right app if and when this gets added to the play store.
